run:
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true

output:
  # sorts results by: filepath, line and column
  sort-results: true

linters:
  enable:
    - godox
    - govet
    - whitespace

  disable:
    - ineffassign
    - errcheck
    - staticcheck
    - gosimple
    - stylecheck
    - wsl
    - revive

linter-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

    # enable or disable analyzers by name
    # run `go tool vet help` to see all analyzers
    enable-all: true